# Generated by Django 2.1.2 on 2019-04-23 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models
import enumfields.fields
import multi_email_field.fields
import uuid
import vcs.repo_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_name', django_bleach.models.BleachField(max_length=200)),
                ('percentile_25', models.FloatField()),
                ('percentile_50', models.FloatField()),
                ('upper_threshold', models.FloatField()),
                ('num_cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_projects', models.IntegerField(default=0)),
                ('selection_type', django_bleach.models.BleachField(default='None', max_length=200)),
                ('date', models.DateTimeField()),
                ('project_data', django_bleach.models.BleachField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node', django_bleach.models.BleachField(max_length=200)),
                ('parent', django_bleach.models.BleachField(blank=True, max_length=200)),
                ('useful_lines', models.IntegerField()),
                ('threshold_violations', models.IntegerField()),
                ('full_name', django_bleach.models.BleachField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InsightUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('architecture_type', django_bleach.models.BleachField(max_length=200)),
                ('propagation_cost', models.FloatField()),
                ('useful_lines_of_code', models.IntegerField()),
                ('num_classes', models.IntegerField()),
                ('num_files', models.IntegerField()),
                ('num_files_in_core', models.IntegerField()),
                ('core_size', models.FloatField()),
                ('num_files_overly_complex', models.IntegerField()),
                ('percent_files_overly_complex', models.FloatField()),
                ('useful_lines_of_comments', models.IntegerField()),
                ('useful_comment_density', models.FloatField()),
                ('duplicate_uloc', models.IntegerField()),
                ('percent_duplicate_uloc', models.FloatField()),
                ('revision_id', django_bleach.models.BleachField(default='Not set', max_length=200)),
                ('is_baseline', models.BooleanField(default=False)),
                ('is_core', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django_bleach.models.BleachField(max_length=200)),
                ('grade', django_bleach.models.BleachField(max_length=200)),
                ('grade_value', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='store.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django_bleach.models.BleachField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django_bleach.models.BleachField(max_length=200)),
                ('type', enumfields.fields.EnumField(enum=vcs.repo_type.RepoType, max_length=10)),
                ('description', django_bleach.models.BleachField()),
                ('token', django_bleach.models.BleachField(blank=True, max_length=200)),
                ('topics', django_bleach.models.BleachField(blank=True)),
                ('language', django_bleach.models.BleachField(max_length=200)),
                ('address', django_bleach.models.BleachField(blank=True, max_length=200)),
                ('allowed_emails', multi_email_field.fields.MultiEmailField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='store.Organization')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='store.Repository'),
        ),
        migrations.AddField(
            model_name='insightuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='store.Organization'),
        ),
        migrations.AddField(
            model_name='insightuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentmeasurement',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_measurements', to='store.Measurement'),
        ),
        migrations.AddField(
            model_name='benchmarkdescription',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_descriptions', to='store.Repository'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='store.Repository'),
        ),
    ]
