# Generated by Django 2.2 on 2019-08-05 19:27

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='log',
            field=django_bleach.models.BleachField(default='', max_length=200),
        ),
    ]
