# Generated by Django 2.2 on 2019-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_repository_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='components_str',
            field=models.TextField(blank=True, default=''),
        ),
    ]
