# Generated by Django 2.2 on 2019-08-27 19:28

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_measurement_components_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='log',
            field=django_bleach.models.BleachField(default=''),
        ),
    ]
